# -*- coding: utf-8 -*-
"""SVM_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rashmibenni292-benni/SVM-Classification-ML-Project/blob/main/SVM_Classification.ipynb
"""

import os

folders = [
    "data/raw",
    "data/processed",
    "results",
    "src",
    "notebooks"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project structure created successfully!")

from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.to_csv("data/raw/breast_cancer.csv", index=False)

"""## 📌 Dataset Description

- Dataset: Breast Cancer Wisconsin
- Source: sklearn.datasets
- Samples: 569
- Features: 30 numeric features
- Target:
  - 0 → Malignant
  - 1 → Benign
- Missing Values: None

"""

df.head()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="target", data=df)
plt.title("Class Distribution")
plt.savefig("results/class_distribution.png")
plt.show()

X = df.drop("target", axis=1)
y = df["target"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""## ⚠️ Feature scaling is essential for SVM because it relies on distance-based optimization.

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

from sklearn.svm import SVC

svm_model = SVC(
    kernel="rbf",
    C=1.0,
    gamma="scale",
    random_state=42
)

svm_model.fit(X_train, y_train)

"""### SVM Configuration
- Kernel: RBF (non-linear decision boundary)
- C: Regularization parameter
- Gamma: Controls influence of training points

"""

y_pred = svm_model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.savefig("results/confusion_matrix.png")
plt.show()

from sklearn.model_selection import GridSearchCV

param_grid = {
    "C": [0.1, 1, 10],
    "gamma": [0.01, 0.1, 1],
    "kernel": ["rbf"]
}

grid = GridSearchCV(
    SVC(),
    param_grid,
    cv=5,
    scoring="accuracy",
    verbose=2
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_
print("Best Parameters:", grid.best_params_)

y_best_pred = best_model.predict(X_test)

print(classification_report(y_test, y_best_pred))

"""## 🔍 Model Interpretation

- Tuned SVM improved generalization
- Achieved high precision and recall
- Low false negatives (critical for medical diagnosis)

"""

processed_df = pd.DataFrame(X_scaled, columns=X.columns)
processed_df["target"] = y.values

processed_df.to_csv("data/processed/processed_data.csv", index=False)

requirements = """
numpy
pandas
scikit-learn
matplotlib
seaborn
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created!")